First part of backend, implementation API.
java-park-mail-ru/osmos-09-2016 pull request #1
Opened 2016-10-04 15:38 UTC by sergey90x

2016-10-04 21:58 UTC, KSolovyev commented
папку /target/ в .gitignore и удалите ее из проекта

2016-10-05 16:23 UTC, d-frolov reviewed
все .DS_Store выкиньте пожалуйста. Это мусор!

2016-10-05 16:23 UTC, d-frolov commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Это мусор в репозитории

2016-10-05 16:23 UTC, d-frolov commented on .idea/.name
> +L1.1
мусор

2016-10-05 16:23 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    private static Map<Integer, UserProfile> userProfiles;
А почему у вас userProfile - static, a userSession - нет?

2016-10-05 16:23 UTC, d-frolov commented on pom.xml
> +    <artifactId>L1.1</artifactId>
Замените в artifactId на название своего проекта,
а старый iml-ник сотрите

2016-10-05 21:28 UTC, d-frolov requested changes

2016-10-05 21:28 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    public int[] addSession(String login) {
неудачный подход
Если у вас сессия - составной объект, то сделайте такой класс

2016-10-05 21:28 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    public Collection getSessions() {
Вы возвращаете абстрактную коллекцию или все-таки коллекцию  Integer-ов?
Да, и тут тоже лучше возвращать объект сессии - если он действительно должен быть составным

2016-10-05 21:28 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    public boolean existingUserById(Integer id){
Обычно, если что-то получаете, то такие методы в Java принято называть начиная с get

2016-10-05 21:28 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +        return 101;
Вот такой подход я не очень понял.
Что такое 101?

Возвращайте либо null, либо сделайте константу в том-же классе Session - Session.INVALID

2016-10-05 21:28 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +            if(login == value.getLogin()){
В Java таким образом объекты сравнивать нельзя
На рк спрошу почему :)

2016-10-06 06:15 UTC, sergey90x commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    private static Map<Integer, UserProfile> userProfiles;
Static использую чтобы произвести инициализацию в статическом блоке, в userProfile я создаю нескольких пользователей, чтобы у меня была не пустая база данных.
А userSession, изначально у меня пустой map.
Я представлял, что так должно быть.

2016-10-06 07:48 UTC, sergey90x commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил.

2016-10-06 07:48 UTC, sergey90x commented on .idea/.name
> +L1.1
Удалил

2016-10-06 07:48 UTC, sergey90x commented on pom.xml
> +    <artifactId>L1.1</artifactId>
Заменил

2016-10-06 07:50 UTC, sergey90x commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    public boolean existingUserById(Integer id){
Прошу прощения, а какой метод вы имеет ввиду?

2016-10-14 20:33 UTC, d-frolov commented
Сделайте пожалуйста 
git rm .idea/ -r
У вас Files changed 97, не возможно на это смотреть :(

2016-10-14 20:51 UTC, d-frolov commented
git rm L1.1.iml

2016-10-14 21:02 UTC, d-frolov commented
Подгрузите профиль инспекций из https://github.com/KSolovyev/tp_java/blob/master/tp_java.xml
и прогоните его по коду

2016-10-14 21:06 UTC, d-frolov commented on src/main/java/ru/mail/park/FakeDB/UserDao.java
> +    private static Map<Integer, UserProfile> userProfiles;
Static здесь лишний. Когда переведете на БД избавьтесь от этого. Сейчас ок.

2016-10-20 16:38 UTC, merged