РК2
java-park-mail-ru/osmos-09-2016 pull request #3
Opened 2016-10-27 16:58 UTC by sergey90x

2016-10-30 16:01 UTC, KSolovyev requested changes

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/ResponseInJson/GetSession.java
> +package ru.mail.park.ResponseInJson;
название пакетов должны начинаться с маленькой буквы

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    // TODO check password
все правильно написано

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RestErrorHandler.java
> +//public class RestErrorHandler {
это надо либо удалить, либо починить

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileDAO.java
> +public interface UserProfileDAO {
поправьте инспекции в этом классе

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/servicies/AccountService.java
>  public class AccountService {
поправьте инспекции в этом классе

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    // TODO пароли отдаём наружу? совсем ужас - надо переделать и не отдавать
вот тут правда написана. надо поправить

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
не используется, надо удалить

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +    // TODO надо как-то ограничить результат и никогда не доставать всех
может сделаем топ100?

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RestErrorHandler.java
> +//public class RestErrorHandler {
скорее починить, потому что случай ошибки базы мы должны как-то обработать

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +    entityManager.persist(user);
что будет, если пользователь с таким именем или почтой уже есть?

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    Integer loggedInUserId = (Integer) httpSession.getAttribute("userId");
вот тут может получиться null, надо обработать

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +  public ResponseEntity<?> login(@RequestBody RegistrationRequest body) {
метод называется login, но делает он регистрацию

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    // TODO check password
а еще надо что-то сделать, если пользователь уже был залогинен

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +public class UserProfileImpl implements UserProfileDAO {
Название не оч. Нужно другое

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +        .createQuery("select u from UserProfile u"
в таких местах лучше писать
`"select u from " + UserProfile.class.getSimpleName() + " u"`

2016-10-30 16:01 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/UserProfile.java
> +  private Integer id;
id должен быть long

2016-10-30 16:01 UTC, KSolovyev commented on src/test/java/ru/mail/park/TestUtil.java
> +//public class TestUtil {
Тесты нужно либо починить, либо удалить

2016-11-02 09:32 UTC, sergey90x commented on src/main/java/ru/mail/park/ResponseInJson/GetSession.java
> +package ru.mail.park.ResponseInJson;
Это исправил.

2016-11-02 09:32 UTC, cheremisin-sergey commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    // TODO пароли отдаём наружу? совсем ужас - надо переделать и не отдавать
Это исправил.

2016-11-02 09:32 UTC, cheremisin-sergey commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    Integer loggedInUserId = (Integer) httpSession.getAttribute("userId");
Это исправил.

2016-11-02 09:32 UTC, sergey90x commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +  public ResponseEntity<?> login(@RequestBody RegistrationRequest body) {
Это исправил.

2016-11-02 09:37 UTC, sergey90x commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    // TODO check password
Сделал проверку пароля.
Существования юзера, если existingUserByLogin(login) возвращает юзера то юзер существует, если null то такого логина нет.

2016-11-02 09:46 UTC, sergey90x commented on src/main/java/ru/mail/park/main/RestErrorHandler.java
> +//public class RestErrorHandler {
Пока, что удалил, так как я этот код взял, кое-что пытаясь сделать как в примере и не разбирался о чем он.
Но, я понял, что нужно как-то обрабатывать ошибки бд.

2016-11-02 09:50 UTC, sergey90x commented on src/main/java/ru/mail/park/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception {
Удалил.

2016-11-02 09:50 UTC, cheremisin-sergey commented on src/main/java/ru/mail/park/DAO2/UserProfileDAO.java
> +public interface UserProfileDAO {
У меня вроде никаких инспекций не горит.

2016-11-02 09:51 UTC, sergey90x commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +public class UserProfileImpl implements UserProfileDAO {
Почему? 
Исправил на UserRequestImpl

2016-11-02 09:52 UTC, sergey90x commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +    entityManager.persist(user);
У меня в контроллере происходит проверка на существование юзера.
И если он существует, то возвращается ошибка, уведомление.

2016-11-02 09:57 UTC, sergey90x commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +    // TODO надо как-то ограничить результат и никогда не доставать всех
Да, надо сделать, я просто начал делать API не задумываясь о все деталях и не согласовал с фронтом какие поля нужны и оказалось, что нет поля по которому нужно топ сделать, пока что просто вывожу первых 50 юзеров, но сейчас буду исправлять.

2016-11-02 09:59 UTC, sergey90x commented on src/main/java/ru/mail/park/model/UserProfile.java
> +  private Integer id;
Изменил.

2016-11-06 14:42 UTC, KSolovyev commented
Просьба, пишите осмысленные комментарии для коммитов

2016-11-06 15:03 UTC, KSolovyev requested changes

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileDAO.java
> +public interface UserProfileDAO {
импортируйте профиль еще раз, тут на каждой строке по инспекции

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +public class UserProfileImpl implements UserProfileDAO {
Название было не очень потому что UserProfileImpl - это имплементация UserProfile. А у вас все таки имплементация DAO к UserProfile

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserProfileImpl.java
> +    entityManager.persist(user);
Разве на совпадение почты проверяете?

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserRequestsImpl.java
> +
Нужно как-то обработать. Добавьте здесь логирование

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserRequestsImpl.java
> +
И здесь

2016-11-06 15:03 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/UserForResponse.java
> +public class UserForResponse {
Нет, так делать не надо. Hibernate позволяет замапить несколько сущностей на одну таблицу, но делается это в других целях. Вам нужно разметить исходную сущность с помощью аннотаций или же добавить в UserProfile метод ResponseData toResponseData() (ну или что-то похожее), который внутри отфильтрует ненужное поле

2016-11-11 12:34 UTC, sergey90x commented
Все исправил, то что вы сказали исправить, кроме инспекций.
Я заново создал xml файл,  куда скопировал xml код из tp_java_new.xml, то что вы в блоге оставили. Затем в intellij  preferences -> inspections -> manage -> import inspection.xml.
И все равно я не вижу,  чтобы мне показывались какие-нибудь инспекции.

2016-11-13 11:12 UTC, KSolovyev requested changes

2016-11-13 11:12 UTC, KSolovyev commented on pom.xml
> +		<dependency>
убирайте дупликаты в зависимостях

2016-11-13 11:12 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserRequestsDAO.java
> +public interface UserRequestsDAO {
в этом классе серым должны светиться модификаторы доступа. Они здесь не нужны, тк в интерфейсе все методы всегда public

2016-11-13 11:12 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserRequestsDaoImpl.java
> +            log.log(Level.INFO, "NoResultExecptin existingUserByLogin");
поправьте опечатеу, пожалуйтса

2016-11-13 11:12 UTC, KSolovyev commented on src/main/java/ru/mail/park/DAO2/UserRequestsDAO.java
> +package ru.mail.park.DAO2;
Почему пакет называется DAO2?

2016-11-13 11:12 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +          e.printStackTrace();
надо использовать логгер. И еще одно каждый раз, когда вы глотаете исключение пользователь вместо сообщения об ошибке получит пустую таблицу (которая иногда может быть валидным вариантом). Это точно то, чего вы хотите?

2016-11-13 11:12 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +          e.printStackTrace();
Это все в том случае, если у вас фронт не развалится от пустого json'а

2016-11-13 17:25 UTC, KSolovyev commented
На счет инспекций очно посмотрим

2016-11-14 21:10 UTC, sergey90x commented
Исправил. С инспекциями все в порядке, они работают, я просто ожидал желтое подсвечивание и не обратил внимание на серое.

2016-11-14 21:57 UTC, KSolovyev commented
последняя просьба: уберите закоментированный код. И будем мержить

2016-11-14 22:21 UTC, sergey90x commented
Убрал.

2016-11-15 13:55 UTC, merged

2016-11-15 21:25 UTC, KSolovyev commented
За вами еще тесты. Их давайте сделаем отдельным пул реквестом