Tests
java-park-mail-ru/osmos-09-2016 pull request #4
Opened 2016-12-10 09:16 UTC by sergey90x

Тесты еще не проверены.

2016-12-11 17:00 UTC, KSolovyev commented
тесты падают

2016-12-11 17:00 UTC, KSolovyev requested changes

2016-12-11 17:00 UTC, KSolovyev commented on src/test/java/ru/mail/park/service/TestService.java
> +public class TestService {
А зачем два одинаковых тестовых класса? И назовите его как-нибудь по-другому

2016-12-15 12:28 UTC, sergey90x commented
Тесты сейчас должны проходить, 
Я удалил пакет service c классом TestService, так как это тоже самое, что и класс TestService в services. При мердже получилось так.

2016-12-15 20:27 UTC, KSolovyev commented
![image](https://cloud.githubusercontent.com/assets/4122313/21240813/f6b30014-c31d-11e6-8a0a-41585fc362f2.png)

2016-12-15 20:27 UTC, merged